### ISSUE TITLE
Verificar que nadie olvidó hacer el build al enviar una PR

### ISSUE THREAD

**Issue by mdelapenya** [gdgtoledo/web#103]
La PR debe romperse si hay cambios en los ficheros generados por el build de jekyll. Lo más sencillo sería reutilizar el script que comprueba el git_state y fallar el build si hay cambios, usando una github action para la automatización: cuando se envíe una PR, hacer el jekyll build, y si hay cambios, fallar la PR con un mensaje esclarecedor:

Se me ocurre: 

> El build se ha roto porque no has lanzado "make build" en tu local
![image](https://user-images.githubusercontent.com/951580/76855365-4788aa80-6851-11ea-9f72-c2d2025582e9.png)
Anda, tira y lanza el build asegurándote de meter el código generado (todo lo que está dentro del `docs`) en un commit separadito)

**Comment by javierlopezdeancos** [comment]
jajaja

**Comment by javierlopezdeancos** [comment]
el commit separadito que ponga algo como

"build X.Y.Z"

**Comment by mdelapenya** [comment]
> el commit separadito que ponga algo como
> 
> "build X.Y.Z"

La PR que se envía tras el merge a master pone como mensaje: `generated: build static files`
