### ISSUE TITLE
Las url de los estáticos no es correcta

### ISSUE THREAD

**Issue by mdelapenya** [gdgtoledo/web#11]
las imágenes son cargadas de `/assets/images/meetups/2017-12-02-vueling-aprendiendo-vue/rafa-explicando.jpg` en lugar de `/web/assets/images/meetups/2017-12-02-vueling-aprendiendo-vue/rafa-explicando.jpg`

**Comment by javierlopezdeancos** [comment]
resolved on https://github.com/gdgtoledo/web/pull/28
