### ISSUE TITLE
En la lista de meetups, clicando en el speaker da error 404

### ISSUE THREAD

**Issue by mdelapenya** [gdgtoledo/web#110]
Debería llevar a la URL del meetup, anteponiendo el contextPath del blog, y no lo hace

**Comment by javierlopezdeancos** [comment]
Creo que da un 404 porque intenta acceder a la url del speaker que  hay definida en los meta data, sea la url del speaker en la propia pagina gdg como miembro o la que le interese poner

**Comment by javierlopezdeancos** [comment]
me respondo a mi mismo, es por una cuestion de que el href no esta correctamente seteado con la direccion relativa

**Comment by javierlopezdeancos** [comment]
![Screenshot_20200318_184354](https://user-images.githubusercontent.com/1202463/76990571-75044f80-6948-11ea-8d82-d8e244c5899e.png)

**Comment by mdelapenya** [comment]
lo tengo solucionado en una rama, luego envío PR
