### ISSUE TITLE
El footer, al estar siempre presente, deja textos a medias 

### ISSUE THREAD

**Issue by mdelapenya** [gdgtoledo/web#117]
<img width="1440" alt="Screenshot 2020-03-20 at 08 21 27" src="https://user-images.githubusercontent.com/951580/77143550-d846cc80-6a83-11ea-9c84-259c62602d51.png">

Me ocurre sin hacer ningún el scroll en la página

¿Es un bug o una feature? 🤔

**Comment by javierlopezdeancos** [comment]
El footer es sticky, está diseñado así, hay varias opciones

- quitar el footer
- quitar que sea stiky, esto haría que si por ejemplo tenemos una pagina con poca altura, por ejemplo la de posts ahora mismo con solo un post, el footer se colocaria detras de ese listado de post, apareciendo muy arriba
- Dejarlo como esta, colocar un borde fino gris arriba para notar el footer y usarlo para incluir mas información interesante no lo de hecho por blablabla, por ejemplo, links a, redes sociales, github, codigo de conducta, whatever

**Comment by mdelapenya** [comment]
Me gusta la tercera opción
