### ISSUE TITLE
Documentar build process

### ISSUE THREAD

**Issue by mdelapenya** [gdgtoledo/web#12]
Hay que instalar Ruby 2.4.2 + Jekyll 3.7.0 + bundle

**Comment by javierlopezdeancos** [comment]
Vamos que hay que crear un readme y te perdiste mi charla de jekyll @mdelapenya jaja

**Comment by avcconti** [comment]
Propongo README con instrucciones de Docker, al final en mi caso he usado Docker, el proceso de instalación del entorno era demasiado costoso.
