### ISSUE TITLE
Enlace superior en menu para ir a lista de posts no funciona y da 404

### ISSUE THREAD

**Issue by javierlopezdeancos** [gdgtoledo/web#16]
En el menu superior derecho, el item `posts` no funciona y no encuentra la pagina a la que enlazar dando un 404.

Curiosamente en la parte de abajo, en el botón `ver todos los posts` esta funcionalidad si está funcionando.

ℹ️ En local el comportamiento si es el adecuado.

![postsnotwork](https://user-images.githubusercontent.com/1202463/60106738-00f49c80-9766-11e9-912c-616e2f83f043.gif)

**Comment by avcconti** [comment]
Fixed with [https://github.com/gdgtoledo/web/pull/17]()
