### ISSUE TITLE
Change domain name, ur in config.yml

### ISSUE THREAD

**Issue by javierlopezdeancos** [gdgtoledo/web#20]
cambiar `domain name`, `url` y algunas variables relativas al repositorio de gdg y no el respectivo a Javi.

```
domain_name: 'https://javierlopezdeancos.github.io'
```

```
url:  'https://javierlopezdeancos.github.io'
```

**Comment by avcconti** [comment]
Pasa versión de Jekyll y ruby que usas, que al meter paginatev2 y autopages sa jodio el arranque con docker, es por intentar montar un dockerfile de 0 compatible con eso.

**Comment by avcconti** [comment]
Forget lo de antes, ya conseguí arrancarlo con config nueva.
