### ISSUE TITLE
Añadir lista de documentos de la colección

### ISSUE THREAD

**Issue by antoniocrevel** [gdgtoledo/web#27]
Creo que los enlaces de las *collections* deberían llevar a una página que te listara todos los documentos de la colección (posts, meetups, etc.).

Yo pensaba que esto debía ser automático y que Jekyll lo renderizaría con sólo configurarlo en el `_config.yml`, pero no lo he conseguido hacer. ¿Sabéis cómo hacer esto?

En cualquier caso, si se quiere tener control total sobre esa lista, lo suyo es crear un documento en el directorio raíz con el mismo nombre que le hayas dado a la colección y construir la lista con con Liquid.

¿Es buena idea crear documentos para listar las colecciones o sabéis cómo hacer esto por configuración?

**Comment by javierlopezdeancos** [comment]
Ahora mismo en nuesta web se está haciendo esto, tenemos unos enlaces a post, meetups donde se enlaza a pagins que listan estos items de las direfentes colecciones, incluso si los queremos paginados tambien podríamos.


Puedes mandar un gif/video de tu duda exacta en la pagina?

**Comment by antoniocrevel** [comment]
Lancé esta issue porque navegando por la web, no lograba ver ni la lista de meetups, ni la de posts, como podéis ver en este vídeo: https://www.loom.com/share/d1b1f9ee7b2e4fdc800c8edaa70a1e88

He visto cómo está montado todo en `_layouts`, y trataré de ver por qué no se están mostrando.

**Comment by antoniocrevel** [comment]
Levantado con Docker y comprobado que todo funciona correctamente y que se listan meetups y posts.
