### ISSUE TITLE
Añadir documentos para los meetups del 2019

### ISSUE THREAD

**Issue by antoniocrevel** [gdgtoledo/web#32]
Aunque todos son necesarios, tener al menos cargados los meetups del 2019.
Deberían estar para el mvp.

**Comment by javierlopezdeancos** [comment]
Venga vamos creando una issue por cada meetup? hacemos aqui la meta issue???? es decir, ponemos una lista de meetups del 2019 y sus ponentes para luego hacer una issue con cada uno de ellos? creo que esta deberia ir en otro milestone llamado, añadir meetups 2019

**Comment by mdelapenya** [comment]
Venga, pongamos en el comentario principal las subtareas 💪

**Comment by antoniocrevel** [comment]
Cada meetup no supone más de 45 minutos si hay que buscar fotos y otros recursos en Twitter o meetup.com. Y no llega a 10 minutos si no hay recursos que enlazar.

Por cierto, los de 2019 ya están hechos, pendiente sólo de que @mdelapenya y @javierlopezdeancos me pasen las diapositivas de dos meetups (Elastic y CLI Node Vs Go).

Está ya todo en mi repo con la PR calentita

**Comment by antoniocrevel** [comment]
Creo que la pobre descripción que he puesto en esta issue (y en la  #52 y #53) ha provocado que parezcan `META` cuando realmente no lo son. 

Los links de las issues  #52 y #53 no son a otras issues, si no a los eventos en meetup.com. Lo puse así, porque a partir del evento extraigo sus datos (nombre, asistentes, ponente, descripción), y los vuelco en el _front matter_ o en el _content_, y ya los tenía abiertos en pestañas y no quería perderlos 😬 

Además, creo que extraer, tranformar y cargar cada meetup en la web no supone mucho tiempo y no justifica crear una issue por cada uno de ellos (entre 10 y 45 minutos).

Los meetups del 2019 están ya terminados a falta de las diapositivas comentadas en este [comentario](https://github.com/gdgtoledo/web/issues/32#issuecomment-531666089).

Acabo de cambiar la descripción en las issues  #52 y #53 para aclararlo.
