### ISSUE TITLE
Demasiado espacio entre el logo y la sección siguiente?

### ISSUE THREAD

**Issue by mdelapenya** [gdgtoledo/web#48]
Es una percepción mía, pero creo que hay mucho hueco entre el logo y las secciones

![web-1](https://user-images.githubusercontent.com/951580/64903381-c3921200-d6b7-11e9-826c-bbe19c6b7be7.gif)

**Comment by mdelapenya** [comment]
wdyt @javierlopezdeancos ??

**Comment by javierlopezdeancos** [comment]
si, puede ser, estoy de acuerdo

**Comment by javierlopezdeancos** [comment]
lo metemos como mejora, porque no es un bug.
