### ISSUE TITLE
Los links del menú principal llevan a páginas vacías

### ISSUE THREAD

**Issue by mdelapenya** [gdgtoledo/web#49]
No aparecen los meetups ni los posts

![web-2](https://user-images.githubusercontent.com/951580/64903393-f5a37400-d6b7-11e9-9602-19a59a8670a0.gif)

**Comment by antoniocrevel** [comment]
It works on my computer!! 

https://www.loom.com/share/ff76bf3def9e4525a1b1c211e89476ab

Usando el contenedor que levantamos con docker compose.

**Comment by avcconti** [comment]
Es lo que comentaba con Javi en las beers. Github pages no acepta la gema de jekyll-paginate-v2 que usamos, de manera que cuando intenta hacer build no llega hacerlo correctamente y no genera los enlaces. Esta semana intentaremos arreglarlo.

**Comment by mdelapenya** [comment]
Merged, thanks!

![image](https://media.giphy.com/media/D0WOL0ogZIoG4/giphy.gif)

**Comment by mdelapenya** [comment]
Resuelto en #59
