### ISSUE TITLE
Crear contenido para el post 'Hola Mundo'

### ISSUE THREAD

**Issue by antoniocrevel** [gdgtoledo/web#51]
Habría que redactar una breve presentación del GDG y d lo que hacemos, ya que ahora tan sólo tiene una especie de plantilla.

![hola-mundo](https://user-images.githubusercontent.com/14337386/64924815-d22c1680-d7e8-11e9-8987-36098561e396.png)

**Comment by javierlopezdeancos** [comment]
Jajajaja buena esta, además yo propongo coger este hola mundo y meterlo en un readme, para que la gente vea ejemplos de como se puede colorerar codigo etc

**Comment by antoniocrevel** [comment]
Meterlo en el README de la propia web me parece muy necesario. Ayudará a todo el que quiera aportar. ¿Hay forma de hacer un spin off de una issue?

**Comment by javierlopezdeancos** [comment]
como un spin off? me not understand

**Comment by antoniocrevel** [comment]
Quería decir, crear una issue a partir de otra y con parte de su contenido, y que dejara traza de cómo se creó

**Comment by javierlopezdeancos** [comment]
ahhh ahora si!!!! understood!
