### ISSUE TITLE
Añadir sección para enlaces en meetups

### ISSUE THREAD

**Issue by javierlopezdeancos** [gdgtoledo/web#6]
Necesitamos añadir la sección para visualizar los enlaces de 

* slides
* codigo
* video

de los meetups.

**Comment by antoniocrevel** [comment]
¿La idea es añadir al front matter toda esa info y luego usarla o se pretendía algo más sofisticado (Meetup API)?

**Comment by antoniocrevel** [comment]
He visto que los enlaces aparecen en los comentarios, así que será el front matter el que provea estos datos

**Comment by antoniocrevel** [comment]
Mergeada en la PR #31
