### ISSUE TITLE
Parpadeo de texto en página de Meetup

### ISSUE THREAD

**Issue by Noradrex** [gdgtoledo/web#64]
Con FF, Chrome y Edge se produce un parpadeo al mover el cursor del ratón entre los textos y fechas de los meetups de la página de Meetups.
El parpadeo es constante y molesto en FF y Chrome. En Edge no es apreciable y solo sucede un instante.

**Comment by mdelapenya** [comment]
![web](https://user-images.githubusercontent.com/951580/71087074-96b03800-219b-11ea-96b0-2a84ed1eb4ef.gif)
