### ISSUE TITLE
Incluir el código de conducta que hay publicado en meetup.com

### ISSUE THREAD

**Issue by antoniocrevel** [gdgtoledo/web#66]
Traer a la web el [código de conducta](https://www.meetup.com/es-ES/gdgtoledo_es/pages/25614955/Code_of_Conduct/) y quizá revisarlo o actualizarlo

**Comment by javierlopezdeancos** [comment]
https://gdgtoledo.github.io/web/code-of-conduct/
https://www.meetup.com/es-ES/gdgtoledo_es/pages/25614955/Code_of_Conduct/
