### ISSUE TITLE
Sustituir el formato de los iconos PNG usados en `style.css` por SVG

### ISSUE THREAD

**Issue by antoniocrevel** [gdgtoledo/web#69]
En la sección de recursos de los meetups, para el enlace al evento de meetup.com, para las diapositivas, vídeo y repositorio de código (`_layouts/meetup.html`) se usan estilos que muestran iconos delante del enlace.

Actualmente se está usando el formato png para los iconos definidos en `style.css` y habría que sustituirlos por los equivalentes de material design en formato svg.

**Comment by javierlopezdeancos** [comment]
Arghghgaraghahgahaghaa si, creo que podriamos hacer un fichero que podamos reusar en el cual tengamos el marcado de esos svg

**Comment by antoniocrevel** [comment]
¿SVG Sprites?

**Comment by javierlopezdeancos** [comment]
también podría ser si tuvieramos claro todos los svg que queremos en el diseño, pero creo que no

**Comment by javierlopezdeancos** [comment]
Oh inyectarlos en linea

https://www.howtobuildsoftware.com/index.php/how-do/bkQq/svg-jekyll-liquid-jekyll-extensions-inline-svg-in-css-within-the-jekyll-workflow

nuestra pagina no requiere mucha performance en el rendimiento
